apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: teflon
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: rbaz.com
    http:
      paths:
      - backend:
          serviceName: teflon
          servicePort: 80
        path: /teflon